//
// Generated file, do not edit! Created by nedtool 5.5 from messages/macMessage.msg.
//

#ifndef __MACMESSAGE_M_H
#define __MACMESSAGE_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0505
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



/**
 * Class generated from <tt>messages/macMessage.msg:19</tt> by nedtool.
 * <pre>
 * //
 * // TODO generated message class
 * //
 * packet macMessage
 * {
 * }
 * </pre>
 */
class macMessage : public ::omnetpp::cPacket
{
  protected:

  private:
    void copy(const macMessage& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const macMessage&);

  public:
    macMessage(const char *name=nullptr, short kind=0);
    macMessage(const macMessage& other);
    virtual ~macMessage();
    macMessage& operator=(const macMessage& other);
    virtual macMessage *dup() const override {return new macMessage(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const macMessage& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, macMessage& obj) {obj.parsimUnpack(b);}


#endif // ifndef __MACMESSAGE_M_H

