//
// Generated file, do not edit! Created by nedtool 5.5 from messages/signalStop.msg.
//

#ifndef __SIGNALSTOP_M_H
#define __SIGNALSTOP_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0505
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



/**
 * Class generated from <tt>messages/signalStop.msg:19</tt> by nedtool.
 * <pre>
 * //
 * // TODO generated message class
 * //
 * packet signalStop
 * {
 *     int id;
 * 
 * }
 * </pre>
 */
class signalStop : public ::omnetpp::cPacket
{
  protected:
    int id;

  private:
    void copy(const signalStop& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const signalStop&);

  public:
    signalStop(const char *name=nullptr, short kind=0);
    signalStop(const signalStop& other);
    virtual ~signalStop();
    signalStop& operator=(const signalStop& other);
    virtual signalStop *dup() const override {return new signalStop(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
    virtual int getId() const;
    virtual void setId(int id);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const signalStop& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, signalStop& obj) {obj.parsimUnpack(b);}


#endif // ifndef __SIGNALSTOP_M_H

