//
// Generated file, do not edit! Created by nedtool 5.5 from appMessage.msg.
//

#ifndef __APPMESSAGE_M_H
#define __APPMESSAGE_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0505
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



/**
 * Class generated from <tt>appMessage.msg:16</tt> by nedtool.
 * <pre>
 * packet appMessage
 * {
 *     simtime_t timeStamp;
 *     int senderId;
 *     int seqno;
 *     int msgSize;
 * 
 * }
 * </pre>
 */
class appMessage : public ::omnetpp::cPacket
{
  protected:
    ::omnetpp::simtime_t timeStamp;
    int senderId;
    int seqno;
    int msgSize;

  private:
    void copy(const appMessage& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const appMessage&);

  public:
    appMessage(const char *name=nullptr, short kind=0);
    appMessage(const appMessage& other);
    virtual ~appMessage();
    appMessage& operator=(const appMessage& other);
    virtual appMessage *dup() const override {return new appMessage(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
    virtual ::omnetpp::simtime_t getTimeStamp() const;
    virtual void setTimeStamp(::omnetpp::simtime_t timeStamp);
    virtual int getSenderId() const;
    virtual void setSenderId(int senderId);
    virtual int getSeqno() const;
    virtual void setSeqno(int seqno);
    virtual int getMsgSize() const;
    virtual void setMsgSize(int msgSize);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const appMessage& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, appMessage& obj) {obj.parsimUnpack(b);}


#endif // ifndef __APPMESSAGE_M_H

