//
// Generated file, do not edit! Created by nedtool 5.5 from selfMessage.msg.
//

#ifndef __SELFMESSAGE_M_H
#define __SELFMESSAGE_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0505
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



/**
 * Class generated from <tt>selfMessage.msg:19</tt> by nedtool.
 * <pre>
 * //
 * // TODO generated message class
 * //
 * packet SelfMessage
 * {
 *     string description;
 *     double totalPower;
 * }
 * </pre>
 */
class SelfMessage : public ::omnetpp::cPacket
{
  protected:
    ::omnetpp::opp_string description;
    double totalPower;

  private:
    void copy(const SelfMessage& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const SelfMessage&);

  public:
    SelfMessage(const char *name=nullptr, short kind=0);
    SelfMessage(const SelfMessage& other);
    virtual ~SelfMessage();
    SelfMessage& operator=(const SelfMessage& other);
    virtual SelfMessage *dup() const override {return new SelfMessage(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
    virtual const char * getDescription() const;
    virtual void setDescription(const char * description);
    virtual double getTotalPower() const;
    virtual void setTotalPower(double totalPower);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const SelfMessage& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, SelfMessage& obj) {obj.parsimUnpack(b);}


#endif // ifndef __SELFMESSAGE_M_H

