//
// Generated file, do not edit! Created by nedtool 5.5 from signalStart.msg.
//

#ifndef __SIGNALSTART_M_H
#define __SIGNALSTART_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0505
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



/**
 * Class generated from <tt>signalStart.msg:19</tt> by nedtool.
 * <pre>
 * //
 * // TODO generated message class
 * //
 * packet SignalStart
 * {
 *     double transmitPowerDBm;
 *     double posX;
 *     double posY;
 *     int id;
 *     bool collidedFlag = false;
 * 
 * 
 * }
 * </pre>
 */
class SignalStart : public ::omnetpp::cPacket
{
  protected:
    double transmitPowerDBm;
    double posX;
    double posY;
    int id;
    bool collidedFlag;

  private:
    void copy(const SignalStart& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const SignalStart&);

  public:
    SignalStart(const char *name=nullptr, short kind=0);
    SignalStart(const SignalStart& other);
    virtual ~SignalStart();
    SignalStart& operator=(const SignalStart& other);
    virtual SignalStart *dup() const override {return new SignalStart(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
    virtual double getTransmitPowerDBm() const;
    virtual void setTransmitPowerDBm(double transmitPowerDBm);
    virtual double getPosX() const;
    virtual void setPosX(double posX);
    virtual double getPosY() const;
    virtual void setPosY(double posY);
    virtual int getId() const;
    virtual void setId(int id);
    virtual bool getCollidedFlag() const;
    virtual void setCollidedFlag(bool collidedFlag);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const SignalStart& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, SignalStart& obj) {obj.parsimUnpack(b);}


#endif // ifndef __SIGNALSTART_M_H

