//
// Generated file, do not edit! Created by nedtool 5.5 from transmissionReq.msg.
//

#ifndef __TRANSMISSIONREQ_M_H
#define __TRANSMISSIONREQ_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0505
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



/**
 * Class generated from <tt>transmissionReq.msg:19</tt> by nedtool.
 * <pre>
 * //
 * // TODO generated message class
 * //
 * packet TransReq
 * {
 * }
 * </pre>
 */
class TransReq : public ::omnetpp::cPacket
{
  protected:

  private:
    void copy(const TransReq& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const TransReq&);

  public:
    TransReq(const char *name=nullptr, short kind=0);
    TransReq(const TransReq& other);
    virtual ~TransReq();
    TransReq& operator=(const TransReq& other);
    virtual TransReq *dup() const override {return new TransReq(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const TransReq& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, TransReq& obj) {obj.parsimUnpack(b);}


#endif // ifndef __TRANSMISSIONREQ_M_H

