//
// Generated file, do not edit! Created by nedtool 5.5 from transmissionRequest.msg.
//

#ifndef __TRANSMISSIONREQUEST_M_H
#define __TRANSMISSIONREQUEST_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0505
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



/**
 * Class generated from <tt>transmissionRequest.msg:19</tt> by nedtool.
 * <pre>
 * //
 * // TODO generated message class
 * //
 * packet transmissionRequest
 * {
 * }
 * </pre>
 */
class transmissionRequest : public ::omnetpp::cPacket
{
  protected:

  private:
    void copy(const transmissionRequest& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const transmissionRequest&);

  public:
    transmissionRequest(const char *name=nullptr, short kind=0);
    transmissionRequest(const transmissionRequest& other);
    virtual ~transmissionRequest();
    transmissionRequest& operator=(const transmissionRequest& other);
    virtual transmissionRequest *dup() const override {return new transmissionRequest(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const transmissionRequest& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, transmissionRequest& obj) {obj.parsimUnpack(b);}


#endif // ifndef __TRANSMISSIONREQUEST_M_H

