//
// Generated file, do not edit! Created by nedtool 5.5 from transmissionConfirm.msg.
//

#ifndef __TRANSMISSIONCONFIRM_M_H
#define __TRANSMISSIONCONFIRM_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0505
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



/**
 * Class generated from <tt>transmissionConfirm.msg:19</tt> by nedtool.
 * <pre>
 * //
 * // TODO generated message class
 * //
 * packet transmissionConfirm
 * {
 *     string status;
 * 
 * }
 * </pre>
 */
class transmissionConfirm : public ::omnetpp::cPacket
{
  protected:
    ::omnetpp::opp_string status;

  private:
    void copy(const transmissionConfirm& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const transmissionConfirm&);

  public:
    transmissionConfirm(const char *name=nullptr, short kind=0);
    transmissionConfirm(const transmissionConfirm& other);
    virtual ~transmissionConfirm();
    transmissionConfirm& operator=(const transmissionConfirm& other);
    virtual transmissionConfirm *dup() const override {return new transmissionConfirm(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
    virtual const char * getStatus() const;
    virtual void setStatus(const char * status);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const transmissionConfirm& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, transmissionConfirm& obj) {obj.parsimUnpack(b);}


#endif // ifndef __TRANSMISSIONCONFIRM_M_H

